/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProsjekterIndexRouteImport } from './routes/prosjekter/index'
import { Route as MedlemmerIndexRouteImport } from './routes/medlemmer/index'
import { Route as InnstillingerIndexRouteImport } from './routes/innstillinger/index'
import { Route as ArkivIndexRouteImport } from './routes/arkiv/index'
import { Route as VTokenRouteImport } from './routes/v/$token'
import { Route as ProsjekterProjectIdRouteImport } from './routes/prosjekter/$projectId'
import { Route as ArkivWorkIdRouteImport } from './routes/arkiv/$workId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiDevSeedRouteImport } from './routes/api/dev-seed'
import { Route as ApiFilesFileIdRouteImport } from './routes/api/files/$fileId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjekterIndexRoute = ProsjekterIndexRouteImport.update({
  id: '/prosjekter/',
  path: '/prosjekter/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedlemmerIndexRoute = MedlemmerIndexRouteImport.update({
  id: '/medlemmer/',
  path: '/medlemmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const InnstillingerIndexRoute = InnstillingerIndexRouteImport.update({
  id: '/innstillinger/',
  path: '/innstillinger/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivIndexRoute = ArkivIndexRouteImport.update({
  id: '/arkiv/',
  path: '/arkiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjekterProjectIdRoute = ProsjekterProjectIdRouteImport.update({
  id: '/prosjekter/$projectId',
  path: '/prosjekter/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivWorkIdRoute = ArkivWorkIdRouteImport.update({
  id: '/arkiv/$workId',
  path: '/arkiv/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSeedRoute = ApiDevSeedRouteImport.update({
  id: '/api/dev-seed',
  path: '/api/dev-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/api/files/$fileId',
  path: '/api/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/api/upload': typeof ApiUploadRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/innstillinger/': typeof InnstillingerIndexRoute
  '/medlemmer/': typeof MedlemmerIndexRoute
  '/prosjekter/': typeof ProsjekterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/api/upload': typeof ApiUploadRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv': typeof ArkivIndexRoute
  '/innstillinger': typeof InnstillingerIndexRoute
  '/medlemmer': typeof MedlemmerIndexRoute
  '/prosjekter': typeof ProsjekterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/api/upload': typeof ApiUploadRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/innstillinger/': typeof InnstillingerIndexRoute
  '/medlemmer/': typeof MedlemmerIndexRoute
  '/prosjekter/': typeof ProsjekterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/dev-seed'
    | '/api/upload'
    | '/arkiv/$workId'
    | '/prosjekter/$projectId'
    | '/v/$token'
    | '/arkiv/'
    | '/innstillinger/'
    | '/medlemmer/'
    | '/prosjekter/'
    | '/api/auth/$'
    | '/api/files/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/dev-seed'
    | '/api/upload'
    | '/arkiv/$workId'
    | '/prosjekter/$projectId'
    | '/v/$token'
    | '/arkiv'
    | '/innstillinger'
    | '/medlemmer'
    | '/prosjekter'
    | '/api/auth/$'
    | '/api/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/dev-seed'
    | '/api/upload'
    | '/arkiv/$workId'
    | '/prosjekter/$projectId'
    | '/v/$token'
    | '/arkiv/'
    | '/innstillinger/'
    | '/medlemmer/'
    | '/prosjekter/'
    | '/api/auth/$'
    | '/api/files/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiDevSeedRoute: typeof ApiDevSeedRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ArkivWorkIdRoute: typeof ArkivWorkIdRoute
  ProsjekterProjectIdRoute: typeof ProsjekterProjectIdRoute
  VTokenRoute: typeof VTokenRoute
  ArkivIndexRoute: typeof ArkivIndexRoute
  InnstillingerIndexRoute: typeof InnstillingerIndexRoute
  MedlemmerIndexRoute: typeof MedlemmerIndexRoute
  ProsjekterIndexRoute: typeof ProsjekterIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekter/': {
      id: '/prosjekter/'
      path: '/prosjekter'
      fullPath: '/prosjekter/'
      preLoaderRoute: typeof ProsjekterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medlemmer/': {
      id: '/medlemmer/'
      path: '/medlemmer'
      fullPath: '/medlemmer/'
      preLoaderRoute: typeof MedlemmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innstillinger/': {
      id: '/innstillinger/'
      path: '/innstillinger'
      fullPath: '/innstillinger/'
      preLoaderRoute: typeof InnstillingerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv/': {
      id: '/arkiv/'
      path: '/arkiv'
      fullPath: '/arkiv/'
      preLoaderRoute: typeof ArkivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekter/$projectId': {
      id: '/prosjekter/$projectId'
      path: '/prosjekter/$projectId'
      fullPath: '/prosjekter/$projectId'
      preLoaderRoute: typeof ProsjekterProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv/$workId': {
      id: '/arkiv/$workId'
      path: '/arkiv/$workId'
      fullPath: '/arkiv/$workId'
      preLoaderRoute: typeof ArkivWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-seed': {
      id: '/api/dev-seed'
      path: '/api/dev-seed'
      fullPath: '/api/dev-seed'
      preLoaderRoute: typeof ApiDevSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/api/files/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiDevSeedRoute: ApiDevSeedRoute,
  ApiUploadRoute: ApiUploadRoute,
  ArkivWorkIdRoute: ArkivWorkIdRoute,
  ProsjekterProjectIdRoute: ProsjekterProjectIdRoute,
  VTokenRoute: VTokenRoute,
  ArkivIndexRoute: ArkivIndexRoute,
  InnstillingerIndexRoute: InnstillingerIndexRoute,
  MedlemmerIndexRoute: MedlemmerIndexRoute,
  ProsjekterIndexRoute: ProsjekterIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesFileIdRoute: ApiFilesFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
